restart:
  description: Send a restart command to a ffmpeg based sensor.
  fields:
    entity_id: {description: Name(s) of entities that will restart. Platform dependent.,
      example: binary_sensor.ffmpeg_noise}
start:
  description: Send a start command to a ffmpeg based sensor.
  fields:
    entity_id: {description: Name(s) of entities that will start. Platform dependent.,
      example: binary_sensor.ffmpeg_noise}
stop:
  description: Send a stop command to a ffmpeg based sensor.
  fields:
    entity_id: {description: Name(s) of entities that will stop. Platform dependent.,
      example: binary_sensor.ffmpeg_noise}
