# Describes the format for available calendar services

todoist_new_task:
  description: Create a new task and add it to a project.
  fields:
    content:
      description: The name of the task.
      example: Pick up the mail
    project:
      description: The name of the project this task should belong to. Defaults to Inbox.
      example: Errands
    labels:
      description: Any labels that you want to apply to this task, separated by a comma.
      example: Chores,Deliveries
    priority:
      description: The priority of this task, from 1 (normal) to 4 (urgent).
      example: 2
    due_date_string:
      description: The day this task is due, in natural language.
      example: "tomorrow"
    due_date_lang:
      description: The language of due_date_string.
      example: "en"
    due_date:
      description: The day this task is due, in format YYYY-MM-DD.
      example: "2018-04-01"
