# Describes the format for available automation services

turn_on:
  description: Enable an automation.
  fields:
    entity_id:
      description: Name of the automation to turn on.
      example: 'automation.notify_home'

turn_off:
  description: Disable an automation.
  fields:
    entity_id:
      description: Name of the automation to turn off.
      example: 'automation.notify_home'

toggle:
  description: Toggle an automation.
  fields:
    entity_id:
      description: Name of the automation to toggle on/off.
      example: 'automation.notify_home'

trigger:
  description: Trigger the action of an automation.
  fields:
    entity_id:
      description: Name of the automation to trigger.
      example: 'automation.notify_home'

reload:
  description: Reload the automation configuration.
