configure:
  description: Set attribute of device in deCONZ. See https://home-assistant.io/components/deconz/#device-services for details.
  fields:
    entity:
      description: Entity id representing a specific device in deCONZ.
      example: 'light.rgb_light'
    field:
      description: >-
        Field is a string representing a full path to deCONZ endpoint (when
        entity is not specified) or a subpath of the device path for the
        entity (when entity is specified).
      example: '"/lights/1/state" or "/state"'
    data:
      description: Data is a json object with what data you want to alter.
      example: '{"on": true}'
    bridgeid:
      description: (Optional) Bridgeid is a string unique for each deCONZ hardware. It can be found as part of the integration name.
      example: '00212EFFFF012345'

device_refresh:
  description: Refresh device lists from deCONZ.
  fields:
    bridgeid:
      description: (Optional) Bridgeid is a string unique for each deCONZ hardware. It can be found as part of the integration name.
      example: '00212EFFFF012345'
