# Describes the format for available IHC services

set_runtime_value_bool:
  description: Set a boolean runtime value on the IHC controller.
  fields:
    ihc_id:
      description: The integer IHC resource ID.
    value:
      description: The boolean value to set.

set_runtime_value_int:
  description: Set an integer runtime value on the IHC controller.
  fields:
    ihc_id:
      description: The integer IHC resource ID.
    value:
      description: The integer value to set.

set_runtime_value_float:
  description: Set a float runtime value on the IHC controller.
  fields:
    ihc_id:
      description: The integer IHC resource ID.
    value:
      description: The float value to set.

pulse:
  description: Pulses an input on the IHC controller.
  fields:
    ihc_id:
      description: The integer IHC resource ID.