sign_in:
  description: Sign the controller in to a HEOS account.
  fields:
    username:
      description: The username or email of the HEOS account. [Required]
      example: 'example@example.com'
    password:
      description: The password of the HEOS account. [Required]
      example: 'password'

sign_out:
  description: Sign the controller out of the HEOS account.